default:
  shortname: african_poetics
  collection_desc: African Poetics
  collection: african-poetics
  threads: 20
  data_base: https://cdrhmedia.unl.edu  # (do not include /data/ in path)
  media_base: https://cdrhmedia.unl.edu
  site_url: https://africanpoetics.unl.edu

  variables_html:
    site_url: https://africanpoetics.unl.edu
    image_large: 800
    image_thumb: 150

development:
  api_version: '2.0'
  site_url: https://servername.unl.edu/african-poetics
  es_path: https://servername.unl.edu/elastic
  es_index: cdrhapidev-v2
  media_base: https://servername.unl.edu
  data_base: https://servername.unl.edu/media

production:
  site_url: https://africanpoetics.unl.edu
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v2
  media_base: https://cdrhmedia.unl.edu
  data_base: https://africanpoetics.unl.edu/media
  # allowed_files: config/allowlist.txt
