default:
  shortname: african_poetics
  collection_desc: African Poetics
  collection: african_poetics
  threads: 20
  data_base: https://cdrhmedia.unl.edu  # (do not include /data/ in path)
  media_base: https://cdrhmedia.unl.edu
  site_url: https://africanpoetics.unl.edu

  variables_html:
    site_url: https://africanpoetics.unl.edu
    image_large: 800
    image_thumb: 150

development:
  es_path: https://cdrhdev1.unl.edu/elastic
  es_index: cdrhapidev-v1
  site_url: https://cdrhdev1.unl.edu/african_poetics
  data_base: https://cdrhdev1.unl.edu/media
  media_base: https://cdrhdev1.unl.edu/media
production:
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v1
